"""add_payment_id_to_tickets

Revision ID: 10ecadfb6d35
Revises: d613e93b1640
Create Date: 2026-01-26 18:13:03.986928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ecadfb6d35'
down_revision: Union[str, None] = 'd613e93b1640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('payment_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'payment_id')
    # ### end Alembic commands ###
