"""add_amenities_to_cinema

Revision ID: 1ae8e272ac49
Revises: c5cfbd102374
Create Date: 2025-11-27 00:38:17.214658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ae8e272ac49'
down_revision: Union[str, None] = 'c5cfbd102374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cinema', sa.Column('amenities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cinema', 'amenities')
    # ### end Alembic commands ###
