"""Add user profile fields

Revision ID: 4124b8d0ea00
Revises: 
Create Date: 2025-11-26 22:52:26.098210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4124b8d0ea00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('profile_picture_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Add boolean columns with defaults first as nullable, then update, then make non-nullable
    op.add_column('user', sa.Column('dark_mode', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('newsletter_subscribed', sa.Boolean(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE \"user\" SET dark_mode = FALSE WHERE dark_mode IS NULL")
    op.execute("UPDATE \"user\" SET notifications_enabled = TRUE WHERE notifications_enabled IS NULL")
    op.execute("UPDATE \"user\" SET newsletter_subscribed = FALSE WHERE newsletter_subscribed IS NULL")
    
    # Make the columns non-nullable
    op.alter_column('user', 'dark_mode', nullable=False)
    op.alter_column('user', 'notifications_enabled', nullable=False)
    op.alter_column('user', 'newsletter_subscribed', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'newsletter_subscribed')
    op.drop_column('user', 'notifications_enabled')
    op.drop_column('user', 'dark_mode')
    op.drop_column('user', 'profile_picture_url')
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
