"""add_auth_enhancements_token_blacklist_and_password_reset

Revision ID: 720a2907e35f
Revises: 4fe61a30e2ac
Create Date: 2025-11-27 15:43:55.175997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '720a2907e35f'
down_revision: Union[str, None] = '4fe61a30e2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create tokenblacklist table only if it doesn't exist
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'tokenblacklist' not in inspector.get_table_names():
        op.create_table('tokenblacklist',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('token_jti', sa.String(length=255), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tokenblacklist_token_jti'), 'tokenblacklist', ['token_jti'], unique=True)
        op.create_index(op.f('ix_tokenblacklist_user_id'), 'tokenblacklist', ['user_id'], unique=False)
    
    # Add password reset fields to user table
    op.add_column('user', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_token_expiry')
    op.drop_column('user', 'reset_token')
    op.drop_index(op.f('ix_tokenblacklist_user_id'), table_name='tokenblacklist')
    op.drop_index(op.f('ix_tokenblacklist_token_jti'), table_name='tokenblacklist')
    op.drop_table('tokenblacklist')
    # ### end Alembic commands ###

