"""add_movie_state_field

Revision ID: eb3cb25c198e
Revises: b7626542fb5e
Create Date: 2026-01-27 19:40:40.059730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3cb25c198e'
down_revision: Union[str, None] = 'b7626542fb5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_favorite_user_cinema_unique', table_name='favorite', postgresql_where='(cinema_id IS NOT NULL)')
    op.drop_index('ix_favorite_user_movie_unique', table_name='favorite', postgresql_where='(movie_id IS NOT NULL)')
    
    # Add state column with default value for existing movies
    op.add_column('movie', sa.Column('state', sa.Enum('COMING_SOON', 'SHOWING', 'ENDED', name='moviestate'), nullable=False, server_default='SHOWING'))
    
    # Update state based on release_date for existing movies
    op.execute("""
        UPDATE movie SET state = CASE
            WHEN release_date > CURRENT_DATE THEN 'COMING_SOON'::moviestate
            WHEN release_date <= CURRENT_DATE - INTERVAL '6 months' THEN 'ENDED'::moviestate
            ELSE 'SHOWING'::moviestate
        END
    """)
    
    # Remove server default after updating existing records
    op.alter_column('movie', 'state', server_default=None)
    
    op.drop_index('ix_seat_reservation_active_unique', table_name='seat_reservation', postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'booked'::character varying])::text[]))")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_seat_reservation_active_unique', 'seat_reservation', ['screening_id', 'seat_id'], unique=False, postgresql_where="((status)::text = ANY ((ARRAY['active'::character varying, 'booked'::character varying])::text[]))")
    op.drop_column('movie', 'state')
    op.create_index('ix_favorite_user_movie_unique', 'favorite', ['user_id', 'movie_id'], unique=False, postgresql_where='(movie_id IS NOT NULL)')
    op.create_index('ix_favorite_user_cinema_unique', 'favorite', ['user_id', 'cinema_id'], unique=False, postgresql_where='(cinema_id IS NOT NULL)')
    # ### end Alembic commands ###
